services:
  wordpress:
    image: docker.io/wordpress:7.0.0-php8.3-apache
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: unicorn
      WORDPRESS_DB_PASSWORD: letmein
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: docker.io/mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: unicorn
      MYSQL_PASSWORD: letmein
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: