services:
  web1:
    image: "docker.io/nginx:alpine"
    volumes:
      - type: bind
        source: "./web-content"
        target: "/usr/share/nginx/html"
    ports:
      - "8080:80"

  web2:
    build:
      dockerfile: Containerfile
    ports:
      - "8081:80"

  alpine:
    image: "docker.io/alpine:3.24.1"
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]